### ISSUE TITLE
[BUG] Websocket Egress fails with broken pipe shortly after it started

### ISSUE THREAD

**Issue by imredobos** [livekit/egress#410]
**Describe the bug**
After a short while, Websocket Egress stream fails with broken pipe

**Egress Version**
v1.7.4

**Egress Request**
{"room_name": "{room_name}", "track_id": "{track_id}", "websocket_url": "ws://{endpoint}/ws" }

**Additional context**
Livekit version: v1.4.3
Repository that contains an easily runnable sample: https://github.com/janoskranczler/livekit-egress-test/
It is also reproduced with this synthetic test and in a cloud environment with a production setup

**Logs**
Livekit log:

livekit-egress-test-livekit-1  | 2023-07-05T13:25:15.221Z       INFO    livekit redis/redis.go:92       connecting to redis     {"simple": true, "addr": "redis:6379"}
livekit-egress-test-livekit-1  | 2023-07-05T13:25:15.282Z       WARN    livekit rtcconfig/rtc_unix.go:17        UDP receive buffer is too small for a production set-up {"current": 425984, "suggested": 5000000}
livekit-egress-test-livekit-1  | 2023-07-05T13:25:15.290Z       INFO    livekit service/server.go:220   starting LiveKit server {"portHttp": 7880, "nodeID": "ND_xsFlveN9", "nodeIP": "127.0.0.1", "version": "1.4.3", "rtc.portTCP": 7881, "rtc.portUDP": 7882}
livekit-egress-test-livekit-1  | 2023-07-05T13:25:16.391Z       INFO    livekit service/roomallocator.go:111    selected node for room  {"room": "test_room", "roomID": "RM_W6wdMVtzCnar", "selectedNodeID": "ND_xsFlveN9"}
livekit-egress-test-livekit-1  | 2023-07-05T13:25:16.403Z       INFO    livekit rtc/room.go:331 new participant joined  {"room": "test_room", "roomID": "RM_W6wdMVtzCnar", "pID": "PA_BxGpNQ3F3fyF", "participant": "test_participant", "protocol": 8, "options": {"AutoSubscribe":true}}
livekit-egress-test-livekit-1  | 2023-07-05T13:25:16.404Z       INFO    livekit rtc/room.go:265 participant state changed       {"room": "test_room", "roomID": "RM_W6wdMVtzCnar", "state": "JOINED", "participant": "test_participant", "pID": "PA_BxGpNQ3F3fyF", "oldState": "JOINING"}
livekit-egress-test-livekit-1  | 2023-07-05T13:25:16.405Z       INFO    livekit service/rtcservice.go:263       new client WS connected {"room": "test_room", "roomID": "RM_W6wdMVtzCnar", "participant": "test_participant", "pID": "PA_BxGpNQ3F3fyF", "remote": false, "connID": "CO_F78Ztjc55324", "reconnect": false, "reconnectReason": "RR_UNKOWN", "adaptiveStream": false}
livekit-egress-test-livekit-1  | 2023-07-05T13:25:16.469Z       INFO    livekit rtc/transport.go:602    selected ICE candidate pair     {"room": "test_room", "roomID": "RM_W6wdMVtzCnar", "participant": "test_participant", "pID": "PA_BxGpNQ3F3fyF", "remote": false, "transport": "SUBSCRIBER", "pair": "(local) udp4 host 172.22.0.4:7882 <-> (remote) udp4 host 192.168.24.89:55158"}
livekit-egress-test-livekit-1  | 2023-07-05T13:25:16.508Z       INFO    livekit rtc/room.go:265 participant state changed       {"room": "test_room", "roomID": "RM_W6wdMVtzCnar", "state": "ACTIVE", "participant": "test_participant", "pID": "PA_BxGpNQ3F3fyF", "oldState": "JOINED"}
livekit-egress-test-livekit-1  | 2023-07-05T13:25:16.568Z       INFO    livekit rtc/participant.go:1572 pending track added     {"room": "test_room", "roomID": "RM_W6wdMVtzCnar", "participant": "test_participant", "pID": "PA_BxGpNQ3F3fyF", "remote": false, "trackID": "TR_AMRwGozcHz8qZM", "track": "sid:\"TR_AMRwGozcHz8qZM\"  source:MICROPHONE", "request": "cid:\"179e56b9-b24e-4e95-a61b-72e7c28319b5\"  source:MICROPHONE"}
livekit-egress-test-livekit-1  | 2023-07-05T13:25:16.698Z       INFO    livekit rtc/transport.go:602    selected ICE candidate pair     {"room": "test_room", "roomID": "RM_W6wdMVtzCnar", "participant": "test_participant", "pID": "PA_BxGpNQ3F3fyF", "remote": false, "transport": "PUBLISHER", "pair": "(local) udp4 host 172.22.0.4:7882 <-> (remote) udp4 host 192.168.24.89:54649"}
livekit-egress-test-livekit-1  | 2023-07-05T13:25:16.758Z       INFO    livekit rtc/participant.go:1241 mediaTrack published    {"room": "test_room", "roomID": "RM_W6wdMVtzCnar", "participant": "test_participant", "pID": "PA_BxGpNQ3F3fyF", "remote": false, "kind": "audio", "trackID": "TR_AMRwGozcHz8qZM", "webrtcTrackID": "179e56b9-b24e-4e95-a61b-72e7c28319b5", "rid": "", "SSRC": 3961967548, "mime": "audio/red"}
livekit-egress-test-livekit-1  | 2023-07-05T13:25:18.797Z       INFO    livekit service/twirp.go:128    API RoomService.GetParticipant  {"service": "RoomService", "method": "GetParticipant", "room": "test_room", "participant": "test_participant", "duration": "791.667µs", "status": "200"}
livekit-egress-test-livekit-1  | 2023-07-05T13:25:19.044Z       INFO    livekit service/twirp.go:128    API Egress.StartTrackEgress     {"service": "Egress", "method": "StartTrackEgress", "room": "test_room", "trackID": "TR_AMRwGozcHz8qZM", "outputType": "*livekit.TrackEgressRequest_WebsocketUrl", "egressID": "EG_Za5gXZT7iZN2", "duration": "230.1865ms", "status": "200"}
livekit-egress-test-livekit-1  | 2023-07-05T13:25:19.116Z       INFO    livekit rtc/room.go:331 new participant joined  {"room": "test_room", "roomID": "RM_W6wdMVtzCnar", "pID": "PA_YWh7b2gHwhTj", "participant": "EG_Za5gXZT7iZN2", "protocol": 8, "options": {"AutoSubscribe":false}}
livekit-egress-test-livekit-1  | 2023-07-05T13:25:19.117Z       INFO    livekit rtc/room.go:265 participant state changed       {"room": "test_room", "roomID": "RM_W6wdMVtzCnar", "state": "JOINED", "participant": "EG_Za5gXZT7iZN2", "pID": "PA_YWh7b2gHwhTj", "oldState": "JOINING"}
livekit-egress-test-livekit-1  | 2023-07-05T13:25:19.117Z       INFO    livekit service/rtcservice.go:263       new client WS connected {"room": "test_room", "roomID": "RM_W6wdMVtzCnar", "participant": "EG_Za5gXZT7iZN2", "pID": "PA_YWh7b2gHwhTj", "remote": false, "connID": "CO_frut3RLZdYK9", "reconnect": false, "reconnectReason": "RR_UNKOWN", "adaptiveStream": false}
livekit-egress-test-livekit-1  | 2023-07-05T13:25:19.125Z       INFO    livekit rtc/transport.go:602    selected ICE candidate pair     {"room": "test_room", "roomID": "RM_W6wdMVtzCnar", "participant": "EG_Za5gXZT7iZN2", "pID": "PA_YWh7b2gHwhTj", "remote": false, "transport": "SUBSCRIBER", "pair": "(local) udp4 host 172.22.0.4:7882 <-> (remote) udp4 host 172.22.0.5:56672"}
livekit-egress-test-livekit-1  | 2023-07-05T13:25:19.131Z       INFO    livekit rtc/room.go:265 participant state changed       {"room": "test_room", "roomID": "RM_W6wdMVtzCnar", "state": "ACTIVE", "participant": "EG_Za5gXZT7iZN2", "pID": "PA_YWh7b2gHwhTj", "oldState": "JOINED"}
livekit-egress-test-livekit-1  | 2023-07-05T13:25:19.131Z       INFO    livekit rtc/subscriptionmanager.go:148  subscribing to track    {"room": "test_room", "roomID": "RM_W6wdMVtzCnar", "participant": "EG_Za5gXZT7iZN2", "pID": "PA_YWh7b2gHwhTj", "remote": false, "trackID": "TR_AMRwGozcHz8qZM"}
livekit-egress-test-livekit-1  | 2023-07-05T13:26:11.659Z       INFO    livekit rtc/signalhandler.go:44 client leaving room     {"room": "test_room", "roomID": "RM_W6wdMVtzCnar", "participant": "EG_Za5gXZT7iZN2", "pID": "PA_YWh7b2gHwhTj", "remote": false}
livekit-egress-test-livekit-1  | 2023-07-05T13:26:11.659Z       INFO    livekit rtc/participant.go:664  participant closing     {"room": "test_room", "roomID": "RM_W6wdMVtzCnar", "participant": "EG_Za5gXZT7iZN2", "pID": "PA_YWh7b2gHwhTj", "remote": false, "sendLeave": true, "reason": "CLIENT_REQUEST_LEAVE"}
livekit-egress-test-livekit-1  | 2023-07-05T13:26:11.662Z       INFO    livekit rtc/participant_signal.go:286   closing signal connection       {"room": "test_room", "roomID": "RM_W6wdMVtzCnar", "participant": "EG_Za5gXZT7iZN2", "pID": "PA_YWh7b2gHwhTj", "remote": false}
livekit-egress-test-livekit-1  | 2023-07-05T13:26:11.662Z       INFO    livekit service/rtcservice.go:236       finishing WS connection {"room": "test_room", "roomID": "RM_W6wdMVtzCnar", "participant": "EG_Za5gXZT7iZN2", "pID": "PA_YWh7b2gHwhTj", "remote": false, "connID": "CO_frut3RLZdYK9"}
livekit-egress-test-livekit-1  | 2023-07-05T13:26:11.668Z       ERROR   livekit service/ioinfo.go:76    egress failed   {"egressID": "EG_Za5gXZT7iZN2", "error": "write tcp 172.22.0.5:38496->172.22.0.3:8000: write: broken pipe"}
livekit-egress-test-livekit-1  | github.com/livekit/livekit-server/pkg/service.(*IOInfoService).UpdateEgressInfo
livekit-egress-test-livekit-1  |        /workspace/pkg/service/ioinfo.go:76
livekit-egress-test-livekit-1  | github.com/livekit/psrpc/pkg/server.(*rpcHandlerImpl[...]).handleRequest
livekit-egress-test-livekit-1  |        /go/pkg/mod/github.com/livekit/psrpc@v0.3.1-0.20230528083849-53d664c6d912/pkg/server/rpc.go:161
livekit-egress-test-livekit-1  | github.com/livekit/psrpc/pkg/server.(*rpcHandlerImpl[...]).run.func1.1
livekit-egress-test-livekit-1  |        /go/pkg/mod/github.com/livekit/psrpc@v0.3.1-0.20230528083849-53d664c6d912/pkg/server/rpc.go:109
livekit-egress-test-livekit-1  | 2023-07-05T13:26:11.683Z       WARN    livekit sfu/downtrack.go:1205   could not write blank frame     {"room": "test_room", "roomID": "RM_W6wdMVtzCnar", "participant": "EG_Za5gXZT7iZN2", "pID": "PA_YWh7b2gHwhTj", "remote": false, "trackID": "TR_AMRwGozcHz8qZM", "relayed": false, "error": "io: read/write on closed pipe"}
livekit-egress-test-livekit-1  | 2023-07-05T13:26:11.683Z       INFO    livekit sfu/downtrack.go:883    rtp stats       {"room": "test_room", "roomID": "RM_W6wdMVtzCnar", "participant": "EG_Za5gXZT7iZN2", "pID": "PA_YWh7b2gHwhTj", "remote": false, "trackID": "TR_AMRwGozcHz8qZM", "relayed": false, "direction": "downstream", "mime": "audio/opus", "ssrc": 1237517161, "stats": "t: Wed Jul  5 13:25:19 UTC 2023|Wed Jul  5 13:26:11 UTC 2023|52.36s, sn: 29818|32413, ep: 2596|49.58/s, p: 2596|49.58/s, l: 0|0.0/s|0.00%, b: 141766|21660.8bps|31152, f: 8|0.2/s / 0|Mon Jan  1 00:00:00 UTC 0001, d: 0|0.00/s, bd: 0|0.0bps|0, pp: 0|0.00/s, bp: 0|0.0bps|0, o: 0, c: 48000, j: 225(4687.5us)|328(6833.3us), n:0|0|0|0, pli:0|Mon Jan  1 00:00:00 UTC 0001 / 0|Mon Jan  1 00:00:00 UTC 0001, fir:0|Mon Jan  1 00:00:00 UTC 0001, rtt(ms):3|4, drift(ms):19.50, sr(Hz):48017.86"}

Egress log:

livekit-egress-test-egress-1  | + export TMPDIR=/tmp/lkegress
livekit-egress-test-egress-1  | + TMPDIR=/tmp/lkegress
livekit-egress-test-egress-1  | + rm -rf /var/run/pulse /var/lib/pulse /root/.config/pulse
livekit-egress-test-egress-1  | + pulseaudio -D --verbose --exit-idle-time=-1 --system --disallow-exit
livekit-egress-test-egress-1  | W: [pulseaudio] main.c: Running in system mode, but --disallow-module-loading not set.
livekit-egress-test-egress-1  | N: [pulseaudio] main.c: Running in system mode, forcibly disabling SHM mode.
livekit-egress-test-egress-1  | I: [pulseaudio] main.c: Daemon startup successful.
livekit-egress-test-egress-1  | + '[' -z /tmp/lkegress ']'
livekit-egress-test-egress-1  | + mkdir -p /tmp/lkegress
livekit-egress-test-egress-1  | + exec egress
livekit-egress-test-egress-1  | 2023-07-05T13:25:15.407Z        INFO    egress  redis/redis.go:92       connecting to redis     {"nodeID": "NE_Z72HPUpBf5JR", "clusterID": "", "simple": true, "addr": "redis:6379"}
livekit-egress-test-egress-1  | 2023-07-05T13:25:15.412Z        INFO    egress  stats/monitor.go:135    available CPU cores: 5 max cost: 4.000000       {"nodeID": "NE_Z72HPUpBf5JR", "clusterID": ""}
livekit-egress-test-egress-1  | 2023-07-05T13:25:15.412Z        DEBUG   egress  service/debug.go:24     debug handler disabled  {"nodeID": "NE_Z72HPUpBf5JR", "clusterID": ""}
livekit-egress-test-egress-1  | 2023-07-05T13:25:15.412Z        DEBUG   egress  service/service.go:77   starting service        {"nodeID": "NE_Z72HPUpBf5JR", "clusterID": "", "version": "1.7.4"}
livekit-egress-test-egress-1  | 2023-07-05T13:25:15.412Z        DEBUG   egress  service/templates_server.go:24  starting template server on address localhost:7980      {"nodeID": "NE_Z72HPUpBf5JR", "clusterID": ""}
livekit-egress-test-egress-1  | 2023-07-05T13:25:15.412Z        DEBUG   egress  service/service_deprecated.go:27        service ready   {"nodeID": "NE_Z72HPUpBf5JR", "clusterID": ""}
livekit-egress-test-egress-1  | 2023-07-05T13:25:19.028Z        INFO    egress  service/service.go:111  request received        {"nodeID": "NE_Z72HPUpBf5JR", "clusterID": "", "egressID": "EG_Za5gXZT7iZN2"}
livekit-egress-test-egress-1  | 2023-07-05T13:25:19.030Z        INFO    egress  service/service.go:119  request validated       {"nodeID": "NE_Z72HPUpBf5JR", "clusterID": "", "egressID": "EG_Za5gXZT7iZN2", "request_type": "track", "output_type": "websocket", "room": "test_room", "request": {"Track":{"room_name":"test_room","track_id":"TR_AMRwGozcHz8qZM","Output":{"WebsocketUrl":"ws://ingest:8000/ws"}}}}
livekit-egress-test-egress-1  | 2023-07-05T13:25:19.094Z        DEBUG   egress  server/main.go:169      handler launched        {"nodeID": "NE_Z72HPUpBf5JR", "handlerID": "EGH_UMpi8qtUPPgF", "clusterID": "", "egressID": "EG_Za5gXZT7iZN2"}
livekit-egress-test-egress-1  | 2023-07-05T13:25:19.095Z        INFO    egress  redis/redis.go:92       connecting to redis     {"nodeID": "NE_Z72HPUpBf5JR", "handlerID": "EGH_UMpi8qtUPPgF", "clusterID": "", "egressID": "EG_Za5gXZT7iZN2", "simple": true, "addr": "redis:6379"}
livekit-egress-test-egress-1  | 2023-07-05T13:25:19.110Z        DEBUG   egress  source/sdk.go:282       connecting to room      {"nodeID": "NE_Z72HPUpBf5JR", "handlerID": "EGH_UMpi8qtUPPgF", "clusterID": "", "egressID": "EG_Za5gXZT7iZN2"}
livekit-egress-test-egress-1  | 2023-07-05T13:25:19.121Z        INFO    logger/logger.go:144    received offer for subscriber   {"nodeID": "NE_Z72HPUpBf5JR", "handlerID": "EGH_UMpi8qtUPPgF", "clusterID": "", "egressID": "EG_Za5gXZT7iZN2"}
livekit-egress-test-egress-1  | 2023-07-05T13:25:19.126Z        INFO    logger/logger.go:144    ICE connected   {"nodeID": "NE_Z72HPUpBf5JR", "handlerID": "EGH_UMpi8qtUPPgF", "clusterID": "", "egressID": "EG_Za5gXZT7iZN2"}
livekit-egress-test-egress-1  | 2023-07-05T13:25:19.283Z        INFO    logger/logger.go:144    received offer for subscriber   {"nodeID": "NE_Z72HPUpBf5JR", "handlerID": "EGH_UMpi8qtUPPgF", "clusterID": "", "egressID": "EG_Za5gXZT7iZN2"}
livekit-egress-test-egress-1  | 2023-07-05T13:25:19.324Z        INFO    logger/logger.go:144    track subscribed        {"nodeID": "NE_Z72HPUpBf5JR", "handlerID": "EGH_UMpi8qtUPPgF", "clusterID": "", "egressID": "EG_Za5gXZT7iZN2", "participant": "test_participant", "track": "TR_AMRwGozcHz8qZM", "kind": "audio"}
livekit-egress-test-egress-1  | 2023-07-05T13:25:19.324Z        DEBUG   egress  source/sdk.go:161       track subscribed        {"nodeID": "NE_Z72HPUpBf5JR", "handlerID": "EGH_UMpi8qtUPPgF", "clusterID": "", "egressID": "EG_Za5gXZT7iZN2", "trackID": "TR_AMRwGozcHz8qZM", "mime": "audio/opus"}
livekit-egress-test-egress-1  | 2023-07-05T13:25:19.448Z        DEBUG   egress  pipeline/pipeline.go:166        waiting for start signal        {"nodeID": "NE_Z72HPUpBf5JR", "handlerID": "EGH_UMpi8qtUPPgF", "clusterID": "", "egressID": "EG_Za5gXZT7iZN2"}
livekit-egress-test-egress-1  | 2023-07-05T13:25:19.449Z        INFO    egress  pipeline/watch.go:148   audioAppSrc playing     {"nodeID": "NE_Z72HPUpBf5JR", "handlerID": "EGH_UMpi8qtUPPgF", "clusterID": "", "egressID": "EG_Za5gXZT7iZN2"}
livekit-egress-test-egress-1  | 2023-07-05T13:25:19.585Z        INFO    egress  pipeline/watch.go:152   pipeline playing        {"nodeID": "NE_Z72HPUpBf5JR", "handlerID": "EGH_UMpi8qtUPPgF", "clusterID": "", "egressID": "EG_Za5gXZT7iZN2"}
livekit-egress-test-egress-1  | 2023-07-05T13:25:19.585Z        INFO    egress  service/handler.go:210  egress updated  {"nodeID": "NE_Z72HPUpBf5JR", "handlerID": "EGH_UMpi8qtUPPgF", "clusterID": "", "egressID": "EG_Za5gXZT7iZN2", "egressID": "EG_Za5gXZT7iZN2", "request_type": "track", "output_type": "websocket", "status": "EGRESS_ACTIVE"}
livekit-egress-test-egress-1  | 2023-07-05T13:25:25.134Z        WARN    egress  sdk/appwriter.go:344    dropping packet {"nodeID": "NE_Z72HPUpBf5JR", "handlerID": "EGH_UMpi8qtUPPgF", "clusterID": "", "egressID": "EG_Za5gXZT7iZN2", "trackID": "TR_AMRwGozcHz8qZM", "kind": "audio", "error": "backwards pts"}
livekit-egress-test-egress-1  | 2023-07-05T13:26:11.650Z        INFO    egress  pipeline/pipeline.go:514        pipeline stopped        {"nodeID": "NE_Z72HPUpBf5JR", "handlerID": "EGH_UMpi8qtUPPgF", "clusterID": "", "egressID": "EG_Za5gXZT7iZN2"}
livekit-egress-test-egress-1  | 2023-07-05T13:26:11.656Z        INFO    egress  sdk/appwriter.go:179    writer finished {"nodeID": "NE_Z72HPUpBf5JR", "handlerID": "EGH_UMpi8qtUPPgF", "clusterID": "", "egressID": "EG_Za5gXZT7iZN2", "trackID": "TR_AMRwGozcHz8qZM", "kind": "audio", "sample duration rtp": 960, "sample duration ns": "20ms", "avg drift": "3.379083ms", "max drift": "29.600791ms"}
livekit-egress-test-egress-1  | 2023-07-05T13:26:11.663Z        INFO    logger/logger.go:144    Leave room      {"nodeID": "NE_Z72HPUpBf5JR", "handlerID": "EGH_UMpi8qtUPPgF", "clusterID": "", "egressID": "EG_Za5gXZT7iZN2", "reason": "CLIENT_INITIATED"}
livekit-egress-test-egress-1  | 2023-07-05T13:26:11.663Z        INFO    egress  service/handler.go:210  egress updated  {"nodeID": "NE_Z72HPUpBf5JR", "handlerID": "EGH_UMpi8qtUPPgF", "clusterID": "", "egressID": "EG_Za5gXZT7iZN2", "egressID": "EG_Za5gXZT7iZN2", "request_type": "track", "output_type": "websocket", "status": "EGRESS_ENDING"}
livekit-egress-test-egress-1  | 2023-07-05T13:26:11.665Z        WARN    egress  service/handler.go:198  egress failed   {"nodeID": "NE_Z72HPUpBf5JR", "handlerID": "EGH_UMpi8qtUPPgF", "clusterID": "", "egressID": "EG_Za5gXZT7iZN2", "egressID": "EG_Za5gXZT7iZN2", "request_type": "track", "output_type": "websocket", "error": "write tcp 172.22.0.5:38496->172.22.0.3:8000: write: broken pipe"}
livekit-egress-test-egress-1  | 2023-07-05T13:26:11.666Z        INFO    egress  pipeline/pipeline.go:397        sending EOS to pipeline {"nodeID": "NE_Z72HPUpBf5JR", "handlerID": "EGH_UMpi8qtUPPgF", "clusterID": "", "egressID": "EG_Za5gXZT7iZN2"}
livekit-egress-test-egress-1  | 2023-07-05T13:26:11.666Z        DEBUG   egress  sdk/appwriter.go:142    draining        {"nodeID": "NE_Z72HPUpBf5JR", "handlerID": "EGH_UMpi8qtUPPgF", "clusterID": "", "egressID": "EG_Za5gXZT7iZN2", "trackID": "TR_AMRwGozcHz8qZM", "kind": "audio"}

**Comment by frostbyte73** [comment]
@imredobos make sure your websocket server is responding to pings, and isn't closing the connection due to timeout. I suspect the websocket server because I can reproduce using https://github.com/janoskranczler/livekit-egress-test/ but I cannot reproduce using the websocket server found [here](https://github.com/livekit/egress/blob/main/test/track.go#L164), even when running for a while

**Comment by imredobos** [comment]
@frostbyte73 I have just made some deeper investigation with ping pong messages, and it seems that the problem is that we are sending ping as well but egress does not send pong for that messages. We are not able to skip sending ping messages, the only solution is to set a very high number for ping interval and timeout as well, which means if the interval is set to 10 minutes and the timeout also set to 10 minutes, the error will happen after 20 minutes. Also we are able to set an unrealistically high number for them, but it would be better if egress would be able to send pong as well.
https://github.com/gorilla/websocket/blob/master/examples/chat/client.go - here is an example how to setup pong handler

**Comment by frostbyte73** [comment]
The default websocket connection does have a default pings handler - the bug here was that we aren't reading from the websocket, so it never receives/handles the pings. Will have a PR soon

**Comment by frostbyte73** [comment]
Fixed in #416 and released in v1.7.6

**Comment by imredobos** [comment]
Something wrong with this fix, I am continuously getting the following error with v1.7.6:
```

panic: repeated read on failed websocket connection
--
 
goroutine 236 [running]:
github.com/gorilla/websocket.(*Conn).NextReader(0xc00069b600)
/root/go/pkg/mod/github.com/gorilla/websocket@v1.5.0/conn.go:1030 +0x27f
github.com/gorilla/websocket.(*Conn).ReadMessage(0xc1230ed3040ec997?)
/root/go/pkg/mod/github.com/gorilla/websocket@v1.5.0/conn.go:1093 +0x19
github.com/livekit/egress/pkg/pipeline/sink.(*WebsocketSink).Start.func2()
/workspace/pkg/pipeline/sink/websocket.go:57 +0x75
created by github.com/livekit/egress/pkg/pipeline/sink.(*WebsocketSink).Start
/workspace/pkg/pipeline/sink/websocket.go:54 +0xa5

```

**Comment by janoskranczler** [comment]
@frostbyte73 
I still get the error after the keepalive (default 20 sec) times out.
LiveKit
```
livekit-egress-test-livekit-1  | 2023-07-12T07:43:25.026Z       INFO    livekit rtc/signalhandler.go:44 client leaving room     {"room": "test_room", "roomID": "RM_iDHquZCuDo9u", "participant": "EG_aPbA8VY4CVCe", "pID": "PA_6BJrHSWDsiE5", "remote": false}
livekit-egress-test-livekit-1  | 2023-07-12T07:43:25.061Z       INFO    livekit rtc/participant.go:664  participant closing     {"room": "test_room", "roomID": "RM_iDHquZCuDo9u", "participant": "EG_aPbA8VY4CVCe", "pID": "PA_6BJrHSWDsiE5", "remote": false, "sendLeave": true, "reason": "CLIENT_REQUEST_LEAVE"}
livekit-egress-test-livekit-1  | 2023-07-12T07:43:25.070Z       INFO    livekit rtc/participant_signal.go:286   closing signal connection       {"room": "test_room", "roomID": "RM_iDHquZCuDo9u", "participant": "EG_aPbA8VY4CVCe", "pID": "PA_6BJrHSWDsiE5", "remote": false}
livekit-egress-test-livekit-1  | 2023-07-12T07:43:25.051Z       INFO    livekit service/rtcservice.go:236       finishing WS connection {"room": "test_room", "roomID": "RM_iDHquZCuDo9u", "participant": "EG_aPbA8VY4CVCe", "pID": "PA_6BJrHSWDsiE5", "remote": false, "connID": "CO_PBG3BtpE6Lgw"}
livekit-egress-test-livekit-1  | 2023-07-12T07:43:25.125Z       WARN    livekit sfu/downtrack.go:1205   could not write blank frame     {"room": "test_room", "roomID": "RM_iDHquZCuDo9u", "participant": "EG_aPbA8VY4CVCe", "pID": "PA_6BJrHSWDsiE5", "remote": false, "trackID": "TR_AMRUK7ZUYipXbo", "relayed": false, "error": "io: read/write on closed pipe"}
livekit-egress-test-livekit-1  | 2023-07-12T07:43:25.128Z       ERROR   livekit service/ioinfo.go:76    egress failed   {"egressID": "EG_aPbA8VY4CVCe", "error": "websocket: close 1011 (internal server error): keepalive ping timeout"}
livekit-egress-test-livekit-1  | github.com/livekit/livekit-server/pkg/service.(*IOInfoService).UpdateEgressInfo
livekit-egress-test-livekit-1  |        /workspace/pkg/service/ioinfo.go:76
livekit-egress-test-livekit-1  | github.com/livekit/psrpc/pkg/server.(*rpcHandlerImpl[...]).handleRequest
livekit-egress-test-livekit-1  |        /go/pkg/mod/github.com/livekit/psrpc@v0.3.1-0.20230528083849-53d664c6d912/pkg/server/rpc.go:161
livekit-egress-test-livekit-1  | github.com/livekit/psrpc/pkg/server.(*rpcHandlerImpl[...]).run.func1.1
livekit-egress-test-livekit-1  |        /go/pkg/mod/github.com/livekit/psrpc@v0.3.1-0.20230528083849-53d664c6d912/pkg/server/rpc.go:109
```

Egress (I'm not sure if those warns has anything to do with the error)
```
livekit-egress-test-egress-1  | 2023-07-12T08:09:50.588Z        DEBUG   egress  source/sdk.go:161       track subscribed        {"nodeID": "NE_EkhdiKwCUBYu", "handlerID": "EGH_J3TaLBQ8q7eE", "clusterID": "", "egressID": "EG_Ai2QVSaFZdJs", "trackID": "TR_AMAhuvhrJsjFVA", "mime": "audio/opus"}
livekit-egress-test-egress-1  | 0:00:00.660974084    32 0xaaaaf789a990 WARN              cudaloader gstcudaloader.c:169:gst_cuda_load_library: Could not open library libcuda.so.1, libcuda.so.1: cannot open shared object file: No such file or directory
livekit-egress-test-egress-1  | 0:00:00.661419750    32 0xaaaaf789a990 WARN                 nvcodec plugin.c:94:plugin_init: Failed to load cuda library
livekit-egress-test-egress-1  | 0:00:00.821672500    32 0xaaaaf789a990 WARN                 default gstsfelement.c:97:gst_sf_create_audio_template_caps: format 0x120000: 'AVR (Audio Visual Research)' is not mapped
livekit-egress-test-egress-1  | 0:00:00.821693250    32 0xaaaaf789a990 WARN                 default gstsfelement.c:97:gst_sf_create_audio_template_caps: format 0x180000: 'CAF (Apple Core Audio File)' is not mapped
livekit-egress-test-egress-1  | 0:00:00.821832209    32 0xaaaaf789a990 WARN                 default gstsfelement.c:97:gst_sf_create_audio_template_caps: format 0x100000: 'HTK (HMM Tool Kit)' is not mapped
livekit-egress-test-egress-1  | 0:00:00.821846209    32 0xaaaaf789a990 WARN                 default gstsfelement.c:97:gst_sf_create_audio_template_caps: format 0xc0000: 'MAT4 (GNU Octave 2.0 / Matlab 4.2)' is not mapped
livekit-egress-test-egress-1  | 0:00:00.821848917    32 0xaaaaf789a990 WARN                 default gstsfelement.c:97:gst_sf_create_audio_template_caps: format 0xd0000: 'MAT5 (GNU Octave 2.1 / Matlab 5.0)' is not mapped
livekit-egress-test-egress-1  | 0:00:00.821850917    32 0xaaaaf789a990 WARN                 default gstsfelement.c:97:gst_sf_create_audio_template_caps: format 0x210000: 'MPC (Akai MPC 2k)' is not mapped
livekit-egress-test-egress-1  | 0:00:00.821853125    32 0xaaaaf789a990 WARN                 default gstsfelement.c:97:gst_sf_create_audio_template_caps: format 0xe0000: 'PVF (Portable Voice Format)' is not mapped
livekit-egress-test-egress-1  | 0:00:00.821855959    32 0xaaaaf789a990 WARN                 default gstsfelement.c:97:gst_sf_create_audio_template_caps: format 0x160000: 'SD2 (Sound Designer II)' is not mapped
livekit-egress-test-egress-1  | 0:00:00.822012542    32 0xaaaaf789a990 WARN                 default gstsfelement.c:97:gst_sf_create_audio_template_caps: format 0x190000: 'WVE (Psion Series 3)' is not mapped
livekit-egress-test-egress-1  | 2023-07-12T08:09:52.114Z        DEBUG   egress  pipeline/pipeline.go:179        waiting for start signal        {"nodeID": "NE_EkhdiKwCUBYu", "handlerID": "EGH_J3TaLBQ8q7eE", "clusterID": "", "egressID": "EG_Ai2QVSaFZdJs"}
livekit-egress-test-egress-1  | 2023-07-12T08:09:52.116Z        INFO    egress  pipeline/watch.go:223   audioAppSrc playing     {"nodeID": "NE_EkhdiKwCUBYu", "handlerID": "EGH_J3TaLBQ8q7eE", "clusterID": "", "egressID": "EG_Ai2QVSaFZdJs"}
livekit-egress-test-egress-1  | 2023-07-12T08:09:52.126Z        INFO    egress  pipeline/watch.go:227   pipeline playing        {"nodeID": "NE_EkhdiKwCUBYu", "handlerID": "EGH_J3TaLBQ8q7eE", "clusterID": "", "egressID": "EG_Ai2QVSaFZdJs"}
livekit-egress-test-egress-1  | 2023-07-12T08:09:52.126Z        INFO    egress  service/handler.go:210  egress updated  {"nodeID": "NE_EkhdiKwCUBYu", "handlerID": "EGH_J3TaLBQ8q7eE", "clusterID": "", "egressID": "EG_Ai2QVSaFZdJs", "egressID": "EG_Ai2QVSaFZdJs", "requestType": "track", "outputType": "websocket", "status": "EGRESS_ACTIVE"}
livekit-egress-test-egress-1  | 2023-07-12T08:10:32.130Z        INFO    egress  pipeline/pipeline.go:544        pipeline stopped        {"nodeID": "NE_EkhdiKwCUBYu", "handlerID": "EGH_J3TaLBQ8q7eE", "clusterID": "", "egressID": "EG_Ai2QVSaFZdJs"}
livekit-egress-test-egress-1  | 2023-07-12T08:10:32.134Z        INFO    egress  sdk/appwriter.go:180    writer finished {"nodeID": "NE_EkhdiKwCUBYu", "handlerID": "EGH_J3TaLBQ8q7eE", "clusterID": "", "egressID": "EG_Ai2QVSaFZdJs", "trackID": "TR_AMAhuvhrJsjFVA", "kind": "audio", "sampleDuration": "20ms", "avgDrift": "908.167µs", "maxDrift": "5.884374ms", "packetLoss": "0.00%"}
livekit-egress-test-egress-1  | 2023-07-12T08:10:32.135Z        WARN    egress  service/handler.go:198  egress failed   {"nodeID": "NE_EkhdiKwCUBYu", "handlerID": "EGH_J3TaLBQ8q7eE", "clusterID": "", "egressID": "EG_Ai2QVSaFZdJs", "egressID": "EG_Ai2QVSaFZdJs", "requestType": "track", "outputType": "websocket", "error": "websocket: close 1011 (internal server error): keepalive ping timeout"}
```

Our Python websocker server
```
livekit-egress-test-ingest-1  | DEBUG:    ! timed out waiting for keepalive pong
livekit-egress-test-ingest-1  | DEBUG:    ! failing connection with code 1011
livekit-egress-test-ingest-1  | DEBUG:    = connection is CLOSING
livekit-egress-test-ingest-1  | DEBUG:    > CLOSE 1011 (unexpected error) keepalive ping timeout [24 bytes]
livekit-egress-test-ingest-1  | DEBUG:    x half-closing TCP connection
livekit-egress-test-ingest-1  | TRACE:    172.30.0.5:52882 - WebSocket connection lost
livekit-egress-test-ingest-1  | DEBUG:    = connection is CLOSED
livekit-egress-test-ingest-1  | TRACE:    172.30.0.5:52882 - ASGI [2] Receive {'type': 'websocket.disconnect', 'code': 1006}
livekit-egress-test-ingest-1  | 2023-07-12 07:43:25,198 WebSocket connection finished
livekit-egress-test-ingest-1  | TRACE:    172.30.0.5:52882 - ASGI [2] Raised exception
livekit-egress-test-ingest-1  | ERROR:    Exception in ASGI application
livekit-egress-test-ingest-1  | Traceback (most recent call last):
livekit-egress-test-ingest-1  |   File "/root/.cache/pypoetry/virtualenvs/livekit-egress-test-MATOk_fk-py3.10/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 254, in run_asgi
livekit-egress-test-ingest-1  |     result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
livekit-egress-test-ingest-1  |   File "/root/.cache/pypoetry/virtualenvs/livekit-egress-test-MATOk_fk-py3.10/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
livekit-egress-test-ingest-1  |     return await self.app(scope, receive, send)
livekit-egress-test-ingest-1  |   File "/root/.cache/pypoetry/virtualenvs/livekit-egress-test-MATOk_fk-py3.10/lib/python3.10/site-packages/uvicorn/middleware/message_logger.py", line 86, in __call__
livekit-egress-test-ingest-1  |     raise exc from None
livekit-egress-test-ingest-1  |   File "/root/.cache/pypoetry/virtualenvs/livekit-egress-test-MATOk_fk-py3.10/lib/python3.10/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
livekit-egress-test-ingest-1  |     await self.app(scope, inner_receive, inner_send)
livekit-egress-test-ingest-1  |   File "/root/.cache/pypoetry/virtualenvs/livekit-egress-test-MATOk_fk-py3.10/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
livekit-egress-test-ingest-1  |     await super().__call__(scope, receive, send)
livekit-egress-test-ingest-1  |   File "/root/.cache/pypoetry/virtualenvs/livekit-egress-test-MATOk_fk-py3.10/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
livekit-egress-test-ingest-1  |     await self.middleware_stack(scope, receive, send)
livekit-egress-test-ingest-1  |   File "/root/.cache/pypoetry/virtualenvs/livekit-egress-test-MATOk_fk-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 149, in __call__
livekit-egress-test-ingest-1  |     await self.app(scope, receive, send)
livekit-egress-test-ingest-1  |   File "/root/.cache/pypoetry/virtualenvs/livekit-egress-test-MATOk_fk-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
livekit-egress-test-ingest-1  |     raise exc
livekit-egress-test-ingest-1  |   File "/root/.cache/pypoetry/virtualenvs/livekit-egress-test-MATOk_fk-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
livekit-egress-test-ingest-1  |     await self.app(scope, receive, sender)
livekit-egress-test-ingest-1  |   File "/root/.cache/pypoetry/virtualenvs/livekit-egress-test-MATOk_fk-py3.10/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
livekit-egress-test-ingest-1  |     raise e
livekit-egress-test-ingest-1  |   File "/root/.cache/pypoetry/virtualenvs/livekit-egress-test-MATOk_fk-py3.10/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
livekit-egress-test-ingest-1  |     await self.app(scope, receive, send)
livekit-egress-test-ingest-1  |   File "/root/.cache/pypoetry/virtualenvs/livekit-egress-test-MATOk_fk-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
livekit-egress-test-ingest-1  |     await route.handle(scope, receive, send)
livekit-egress-test-ingest-1  |   File "/root/.cache/pypoetry/virtualenvs/livekit-egress-test-MATOk_fk-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 341, in handle
livekit-egress-test-ingest-1  |     await self.app(scope, receive, send)
livekit-egress-test-ingest-1  |   File "/root/.cache/pypoetry/virtualenvs/livekit-egress-test-MATOk_fk-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 82, in app
livekit-egress-test-ingest-1  |     await func(session)
livekit-egress-test-ingest-1  |   File "/root/.cache/pypoetry/virtualenvs/livekit-egress-test-MATOk_fk-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 289, in app
livekit-egress-test-ingest-1  |     await dependant.call(**values)
livekit-egress-test-ingest-1  |   File "/code/main.py", line 17, in websocket_endpoint
livekit-egress-test-ingest-1  |     await websocket.receive_bytes()
livekit-egress-test-ingest-1  |   File "/root/.cache/pypoetry/virtualenvs/livekit-egress-test-MATOk_fk-py3.10/lib/python3.10/site-packages/starlette/websockets.py", line 122, in receive_bytes
livekit-egress-test-ingest-1  |     self._raise_on_disconnect(message)
livekit-egress-test-ingest-1  |   File "/root/.cache/pypoetry/virtualenvs/livekit-egress-test-MATOk_fk-py3.10/lib/python3.10/site-packages/starlette/websockets.py", line 105, in _raise_on_disconnect
livekit-egress-test-ingest-1  |     raise WebSocketDisconnect(message["code"])
livekit-egress-test-ingest-1  | starlette.websockets.WebSocketDisconnect: 1006
```
