### ISSUE TITLE
TrackSynchronizer Bug：Incorrect expected Calculation and Potential Overflow in resetRTP Method

### ISSUE THREAD

**Issue by kendo6666** [livekit/egress#654]
**Description:**

We have identified two critical bugs in the TrackSynchronizer implementation that can significantly impact the synchronization of RTP packets in scenarios where audio and video tracks do not start simultaneously or when there is a significant delay in one of the tracks.

**Bug 1: Incorrect Calculation of expected Leading to Unnecessary resetRTP Calls**

The calculation of the expected playback time does not adequately account for tracks that start at significantly different times. This can lead to scenarios where the expected time is inaccurately calculated, causing unnecessary invocations of the resetRTP method.

```
if expected := time.Since(t.startedAt.Add(t.ptsOffset)); pts > expected+maxTSDiff {
    // reset RTP timestamps
    logger.Debugw("resetting track synchronizer", "reason", "pts out of bounds", "pts", pts, "expected", expected)
    ts, pts = t.resetRTP(pkt)
    return ts, pts, false
}
```

**Bug 2: Overflow in resetRTP Due to Uninitialized lastPacket**

In the resetRTP method, if the first packet transmission has not been completed (t.lastPacket is 0), it results in a calculation of an excessively large frames value. This, in turn, leads to incorrect ts/pts calculations and can cause firstTS to overflow, becoming a large negative number.

```
func (t *TrackSynchronizer) resetRTP(pkt *rtp.Packet) (int64, time.Duration) {
    frames := int64(time.Since(t.lastPacket) / t.getFrameDuration())
    duration := t.getFrameDurationRTP() * frames
    ts := t.lastTS + duration
    pts := t.lastPTS + t.rtpConverter.toDuration(duration)
    t.firstTS += int64(pkt.Timestamp) - ts
    return ts, pts
}
```

**Steps to Reproduce:**

1. Initialize a TrackSynchronizer with a significant delay between audio and video track starts.
2. Observe the calculation of expected leading to unnecessary resetRTP calls due to the incorrect handling of delayed track starts.
3. Send the first RTP packet and observe the calculation in resetRTP, leading to an overflow in firstTS.

**Expected Behavior:**

- The expected playback time should accurately reflect the delay between different tracks starting times.
- The resetRTP method should handle the first packet transmission gracefully without resulting in overflow or incorrect timestamp calculations.
- 
**Actual Behavior:**

- The calculation of expected does not account for delayed track starts, causing unnecessary resetRTP invocations.
- The resetRTP method can overflow firstTS when handling the first packet, due to an uninitialized lastPacket.

**Possible Fix:**

- Revise the calculation of expected to accurately account for the start times of different tracks.
- Initialize lastPacket appropriately or add checks to prevent overflow in resetRTP.

**Additional Information:**

- The issue was observed in scenarios with significant delays between the start times of audio and video tracks.
- The impact includes potential synchronization issues and incorrect handling of RTP packet timestamps.

---

Feel free to adjust the bug report based on your observations and specific details of your implementation.

**Comment by frostbyte73** [comment]
Thanks for digging into this. Fix coming today

**Comment by frostbyte73** [comment]
Fixed in https://github.com/livekit/server-sdk-go/pull/453

**Comment by kendo6666** [comment]
@frostbyte73 
This fixes the overflow bug, but did not resolve the core issue. I believe the core problem lies in all tracks sharing the same ptsOffset, causing the offset of later-entered tracks to be incorrect. It seems that allowing each track to have its own offset would be the correct solution.

`From cae8a7b045d997e889cf22b1be85ab71ff1d53ce Mon Sep 17 00:00:00 2001
From: zm <zm@zm.com>
Date: Thu, 25 Apr 2024 11:45:09 +0800
Subject: [PATCH] Fix one track starting much later than the other

---
 pkg/synchronizer/track.go | 6 ++++--
 1 file changed, 4 insertions(+), 2 deletions(-)

diff --git a/pkg/synchronizer/track.go b/pkg/synchronizer/track.go
index 69ac882..cedfedf 100644
--- a/pkg/synchronizer/track.go
+++ b/pkg/synchronizer/track.go
@@ -76,6 +76,7 @@ type TrackSynchronizer struct {
 	// offsets
 	snOffset  uint16        // sequence number offset (increases with each blank frame inserted
 	ptsOffset time.Duration // presentation timestamp offset (used for a/v sync)
+	trackPtsOffset time.Duration
 }
 
 func newTrackSynchronizer(s *Synchronizer, track TrackRemote) *TrackSynchronizer {
@@ -106,7 +107,8 @@ func (t *TrackSynchronizer) Initialize(pkt *rtp.Packet) {
 	t.Lock()
 	t.startedAt = time.Unix(0, startedAt)
 	t.firstTS = int64(pkt.Timestamp)
-	t.ptsOffset = time.Duration(now - startedAt)
+	t.ptsOffset = time.Duration(0)
+	t.trackPtsOffset = time.Duration(now - startedAt)
 	t.Unlock()
 }
 
@@ -189,7 +191,7 @@ func (t *TrackSynchronizer) adjust(pkt *rtp.Packet) (int64, time.Duration, bool)
 	}
 
 	// sanity check
-	pts := t.getElapsed(ts) + t.ptsOffset
+	pts := t.getElapsed(ts) + t.trackPtsOffset
 	if expected := time.Since(t.startedAt.Add(t.ptsOffset)); pts > expected+maxTSDiff {
 		// reset RTP timestamps
 		logger.Debugw("resetting track synchronizer", "reason", "pts out of bounds", "pts", pts, "expected", expected)
-- 
2.41.0.windows.1
`
