### ISSUE TITLE
Error with track composite using HLS segments

### ISSUE THREAD

**Issue by JacobSteelsmith** [livekit/egress#67]
The egress service works fine on individual tracks and track composite when generating an MP4. Both upload fine to S3 after completion. When attempting to use HLS I get an error below. Wondering if anyone had any insight. Thanks.

{"level":"error","ts":1659482383.8220048,"logger":"egress","caller":"pipeline/pipeline.go:725","msg":"pipeline error","nodeID":"NE_PDiGa63Zs5mz","egressID":"EG_Zy5A33BurgpG","debug":"../libs/gst/base/gstbasesrc.c(3127): gst_base_src_loop (): /GstPipeline:pipeline/GstBin:input/GstAppSrc:videoAppSrc:\nstreaming stopped, reason not-linked (-1)","message":"Internal data stream error.","error":"Internal data stream error.","stacktrace":"github.com/livekit/egress/pkg/pipeline.(*Pipeline).handleError\n\t/workspace/pkg/pipeline/pipeline.go:725\ngithub.com/livekit/egress/pkg/pipeline.(*Pipeline).messageWatch\n\t/workspace/pkg/pipeline/pipeline.go:566\ngithub.com/tinyzimmer/go-gst/gst.goBusFunc\n\t/root/go/pkg/mod/github.com/livekit/go-gst@v0.0.0-20220603230042-cef031256427/gst/cgo_exports.go:128\n_cgoexp_752bbda710ba_goBusFunc\n\t_cgo_gotypes.go:17360\nruntime.cgocallbackg1\n\t/usr/lib/go-1.16/src/runtime/cgocall.go:292\nruntime.cgocallbackg\n\t/usr/lib/go-1.16/src/runtime/cgocall.go:228\nruntime.cgocallback\n\t/usr/lib/go-1.16/src/runtime/asm_arm64.s:1055\nruntime.asmcgocall\n\t/usr/lib/go-1.16/src/runtime/asm_arm64.s:917\nruntime.cgocall\n\t/usr/lib/go-1.16/src/runtime/cgocall.go:164\ngithub.com/tinyzimmer/go-glib/glib._Cfunc_g_main_loop_run\n\t_cgo_gotypes.go:2819\ngithub.com/tinyzimmer/go-glib/glib.(*MainLoop).Run.func1\n\t/root/go/pkg/mod/github.com/tinyzimmer/go-glib@v0.0.25/glib/gmainloop.go:53\ngithub.com/tinyzimmer/go-glib/glib.(*MainLoop).Run\n\t/root/go/pkg/mod/github.com/tinyzimmer/go-glib@v0.0.25/glib/gmainloop.go:53\ngithub.com/livekit/egress/pkg/pipeline.(*Pipeline).Run\n\t/workspace/pkg/pipeline/pipeline.go:210\ngithub.com/livekit/egress/pkg/service.(*Handler).HandleRequest.func2\n\t/workspace/pkg/service/handler.go:59"}

**Comment by frostbyte73** [comment]
Fixed in https://github.com/livekit/egress/pull/68

**Comment by JacobSteelsmith** [comment]
Thanks for the quick reply. I'm still getting the error. I've verified chart/app version v1.1.0 and restarted the pods.

{"level":"debug","ts":1659642872.4782152,"logger":"egress","caller":"pipeline/pipeline.go:639","msg":"[src] STREAM-STATUS - Stream status from audioAppSrc: A thread has entered its loop function","nodeID":"NE_i7qAwrwF3dC4","egressID":"EG_biCm3BdmceMQ"}
{"level":"debug","ts":1659642872.478236,"logger":"egress","caller":"pipeline/pipeline.go:639","msg":"[src] STREAM-STATUS - Stream status from videoAppSrc: A thread has entered its loop function","nodeID":"NE_i7qAwrwF3dC4","egressID":"EG_biCm3BdmceMQ"}
{"level":"debug","ts":1659642872.478256,"logger":"egress","caller":"pipeline/pipeline.go:639","msg":"[pipeline] NEW-CLOCK - Got a new clock","nodeID":"NE_i7qAwrwF3dC4","egressID":"EG_biCm3BdmceMQ"}
{"level":"info","ts":1659642872.4783502,"logger":"egress","caller":"service/handler.go:129","msg":"egress updated","nodeID":"NE_i7qAwrwF3dC4","egressID":"EG_biCm3BdmceMQ","status":"EGRESS_ACTIVE"}
{"level":"debug","ts":1659642872.5335274,"logger":"egress","caller":"pipeline/pipeline.go:639","msg":"[x264enc0] LATENCY - Element's latency has changed","nodeID":"NE_i7qAwrwF3dC4","egressID":"EG_biCm3BdmceMQ"}
{"level":"error","ts":1659642872.6043344,"logger":"egress","caller":"pipeline/pipeline.go:725","msg":"pipeline error","nodeID":"NE_i7qAwrwF3dC4","egressID":"EG_biCm3BdmceMQ","debug":"../libs/gst/base/gstbasesrc.c(3127): gst_base_src_loop (): /GstPipeline:pipeline/GstBin:input/GstAppSrc:videoAppSrc:\nstreaming stopped, reason not-linked (-1)","message":"Internal data stream error.","error":"Internal data stream error.","stacktrace":"github.com/livekit/egress/pkg/pipeline.(*Pipeline).handleError\n\t/workspace/pkg/pipeline/pipeline.go:725\ngithub.com/livekit/egress/pkg/pipeline.(*Pipeline).messageWatch\n\t/workspace/pkg/pipeline/pipeline.go:566\ngithub.com/tinyzimmer/go-gst/gst.goBusFunc\n\t/root/go/pkg/mod/github.com/livekit/go-gst@v0.0.0-20220603230042-cef031256427/gst/cgo_exports.go:128\n_cgoexp_752bbda710ba_goBusFunc\n\t_cgo_gotypes.go:17363\nruntime.cgocallbackg1\n\t/usr/lib/go-1.18/src/runtime/cgocall.go:314\nruntime.cgocallbackg\n\t/usr/lib/go-1.18/src/runtime/cgocall.go:233\nruntime.cgocallback\n\t/usr/lib/go-1.18/src/runtime/asm_arm64.s:1181\nruntime.systemstack_switch\n\t/usr/lib/go-1.18/src/runtime/asm_arm64.s:194\nruntime.cgocall\n\t/usr/lib/go-1.18/src/runtime/cgocall.go:167\ngithub.com/tinyzimmer/go-glib/glib._Cfunc_g_main_loop_run\n\t_cgo_gotypes.go:2822\ngithub.com/tinyzimmer/go-glib/glib.(*MainLoop).Run.func1\n\t/root/go/pkg/mod/github.com/tinyzimmer/go-glib@v0.0.25/glib/gmainloop.go:53\ngithub.com/tinyzimmer/go-glib/glib.(*MainLoop).Run\n\t/root/go/pkg/mod/github.com/tinyzimmer/go-glib@v0.0.25/glib/gmainloop.go:53\ngithub.com/livekit/egress/pkg/pipeline.(*Pipeline).Run\n\t/workspace/pkg/pipeline/pipeline.go:210\ngithub.com/livekit/egress/pkg/service.(*Handler).HandleRequest.func2\n\t/workspace/pkg/service/handler.go:59"}
2022/08/04 19:54:32 "msg"="error with read worker" "error"="read tcp 192.168.46.142:60936->35.163.247.13:443: use of closed network connection"
{"level":"error","ts":1659642872.6049972,"logger":"egress","caller":"service/handler.go:125","msg":"egress failed","nodeID":"NE_i7qAwrwF3dC4","egressID":"EG_biCm3BdmceMQ","error":"Internal data stream error.","stacktrace":"github.com/livekit/egress/pkg/service.(*Handler).sendUpdate\n\t/workspace/pkg/service/handler.go:125\ngithub.com/livekit/egress/pkg/service.(*Handler).HandleRequest\n\t/workspace/pkg/service/handler.go:70\nmain.runHandler\n\t/workspace/cmd/server/main.go:147\ngithub.com/urfave/cli/v2.(*Command).Run\n\t/root/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163\ngithub.com/urfave/cli/v2.(*App).RunContext\n\t/root/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313\ngithub.com/urfave/cli/v2.(*App).Run\n\t/root/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224\nmain.main\n\t/workspace/cmd/server/main.go:65\nruntime.main\n\t/usr/lib/go-1.18/src/runtime/proc.go:250"}

**Comment by frostbyte73** [comment]
@JacobSteelsmith what does your request look like?

**Comment by JacobSteelsmith** [comment]
Thanks again for the quick reply and your assistance. I really appreciate it.

I've attached a full log of a single call to the pod. I'm using webhooks and AWS Lambda to get the participant information including tracks when the track is published. It's strange because I see two webhook calls for egress_started but the function is only calling ec.startTrackCompositeEgress(body.room.name, output, audiot, videot) once. I've attached a screenshot of the log events. The event that has info2 is the result of the await call to startTrackCompositeEgress() so from what I see there is one call but two egress events are recorded from the webhook. 


![Screenshot from 2022-08-04 16-05-51](https://user-images.githubusercontent.com/1895699/182969869-40307e73-ebb8-42cb-ae6b-e12c898efe20.png)


[logs.txt](https://github.com/livekit/egress/files/9264016/logs.txt)

**Comment by frostbyte73** [comment]
it looks like there were 2 egress, with ids `EG_9LCMZ4894WWA` and `EG_qynGC9vkb5wG`. I'll have to

**Comment by JacobSteelsmith** [comment]
Ok. I'll test today with just creating the MP4 rather than using the HLS protocol to see if I see to egress events. The MP4 worked fine the last time I tried but I wasn't looking for two egress events. Thanks again for your time.

**Comment by JacobSteelsmith** [comment]
I see the same thing  with MP4 and that is failing now. I'm still only seeing one result from startTrackCompositeEgress() in cloudwatch and the info logged matches the first egress_id. But the same second I'm seeing a second, separate egress_id being started in both the pod logs and cloudwatch. The MP4 was working previously. I'll keep testing. I'm going to see what happens with just the video does using startTrackEgress().

**Comment by JacobSteelsmith** [comment]
I did get the MP4 to work again by reverting back to the v1.0 docker image. I could not get anything to work, even a singleTrackEgress() call until I re-deployed helm manually setting image.tag=v1.0. Then single track and MP4 work again and I see single egress_started calls.

**Comment by neilkinnish** [comment]
Hi, we are having issues with single track egress also.

We have a different error though `EmptyStaticCreds: static credentials are empty` 

Composite recording all seems fine.

**Comment by neilkinnish** [comment]
Hi, we are having issues with single track egress also.

We have a different error though `EmptyStaticCreds: static credentials are empty` 

I believe we have a correct setup and have tested sending the credentials as well as having defaults – all works for Composite recording.

**Comment by davidzhao** [comment]
> Hi, we are having issues with single track egress also.
> 
> We have a different error though `EmptyStaticCreds: static credentials are empty`
> 
> I believe we have a correct setup and have tested sending the credentials as well as having defaults – all works for Composite recording.
> 
> Just noting here for reference.

@neilkinnish you are describing a very different issue that's unrelated to this one. Please open a new issue if you are still experiencing it. Please provide details about your config and request sent.

**Comment by neilkinnish** [comment]
You are right @davidzhao, it was confusion our end and is now resolved. I meant to update my comment. Thanks.

**Comment by frostbyte73** [comment]
@JacobSteelsmith We were able to reproduce this last week, and it should be fixed now in v1.3.0

**Comment by JacobSteelsmith** [comment]
@frostbyte73 Awesome, thanks so much! I deployed and MP4 seems to be working well. Thanks for your work on this.
